FROM ubi8/ubi:8.3

MAINTAINER Boris Buechel <boris.buechel@de.ibm.com>

LABEL description="A custom Apache container based on UBI 8"

RUN yum install -y httpd && yum clean all

RUN echo "HELLO from Containerfile" > /var/www/html/index.html

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]
